### ISSUE TITLE
[1.14.4-1.0.4] NoSuchMethodError

### ISSUE THREAD

**Issue by kreezxil** [CyclopsMC/Flopper#11] opened 2019-11-20 17:48 UTC
#### Issue type:

- :bug: 
____

#### Short description:

When right clicking a fluid hopper while connected to a server it crashes
#### Steps to reproduce the problem:

1. craft hopper
1. place hopper
1. right click hopper

#### Expected behaviour:

to not crash dedicated server
____

#### Versions:

- This mod: 1.0.4
- Minecraft: 1.14.4
- Forge: 28.1.90

#### Log file:

report name | paste
 ----------- | -----
crash-2019-11-20_12.30.42-server.txt | http://paste.ubuntu.com/p/6W4SnHqR4x/

**Comment by rubensworks** [comment] 2019-11-20 17:48
Duplicate of #8 (which has been fixed yesterday, release coming soon)

**Closed as completed by rubensworks** 2019-11-20 17:48 UTC
